# Generated by Django 5.0.2 on 2024-03-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='title',
            new_name='text_speech',
        ),
    ]
