# Generated by Django 5.0.2 on 2024-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_title_speech_text_speech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('link', models.URLField()),
                ('media', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('owener', models.CharField(max_length=100)),
            ],
        ),
    ]
