# Generated by Django 5.0.2 on 2024-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(),
        ),
    ]
