# Generated by Django 5.0.2 on 2024-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_podcast_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='media',
            field=models.URLField(),
        ),
    ]
