# Generated by Django 5.0.2 on 2024-03-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_userbookmark_link_userbookmark_media_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='media',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
