# Generated by Django 5.0.2 on 2024-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_alter_userbookmark_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='image_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
