# Generated by Django 5.0.2 on 2024-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_userbookmark_image_file_userbookmark_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='image_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
