# Generated by Django 5.0.2 on 2024-03-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_alter_userbookmark_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmark',
            old_name='uploaded_on',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='userbookmark',
            name='media',
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='image_file',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
