# Generated by Django 5.0.2 on 2024-03-23 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_rename_uploaded_on_userbookmark_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='image_file',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
