# Generated by Django 5.0.2 on 2024-03-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_alter_userbookmark_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='image_file',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
